# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build containers
      run: docker-compose build

    - name: Push containers
      run: docker-compose push

    - name: Run application 
      run: docker-compose up

    - name: Run application
      run: docker-compose down
